# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
         node-version: '10.x'

      - name: Test firebase functions
        working-directory: ./functions
        run: npm install && npm run test
      - name: Test front-end
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:4200'
          build: npm run build
          start: npm run start
