# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: closed
    branches: [ prod_v_7_0_0 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firebase-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
         node-version: '10.x'

      - run: npm install
      - run: npm run test-headless
      - run: npm run build:prod

      - uses: w9jds/firebase-action@master
        with:
          args: use token-pow
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:token-pow
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Install npm packages for functions
        run: |
          cd functions
          npm install

      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
